import { PlanDetails, DocumentTemplate, LegalCategory } from '@/types';

export const PLANS: PlanDetails[] = [
  {
    id: 'free',
    name: 'Gratuito',
    price: 0,
    yearlyPrice: 0,
    queriesLimit: 3,
    documentsLimit: 1,
    features: [
      '3 consultas por mes',
      '1 documento simple',
      'Marca de agua en documentos',
      'Acceso a base de conocimiento',
    ],
  },
  {
    id: 'basic',
    name: 'Básico',
    price: 29,
    yearlyPrice: 278,
    queriesLimit: 20,
    documentsLimit: 'unlimited',
    popular: true,
    features: [
      '20 consultas por mes',
      'Documentos ilimitados (básicos)',
      'Sin marca de agua',
      'Historial guardado',
      'Soporte por email',
    ],
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 79,
    yearlyPrice: 758,
    queriesLimit: 'unlimited',
    documentsLimit: 'unlimited',
    features: [
      'Consultas ilimitadas',
      'Todos los documentos',
      'Videollamada 30 min/mes con abogado',
      'Alertas legales personalizadas',
      'Revisión de documentos por IA',
      'Soporte prioritario',
    ],
  },
  {
    id: 'enterprise',
    name: 'Empresarial',
    price: 299,
    yearlyPrice: 2870,
    queriesLimit: 'unlimited',
    documentsLimit: 'unlimited',
    features: [
      'Hasta 20 empleados',
      'Todo lo del plan Premium',
      'Contratos empresariales',
      'Dashboard de gestión',
      'Soporte prioritario 24/7',
      'Capacitación incluida',
    ],
  },
];

export const LEGAL_CATEGORIES: { id: LegalCategory; name: string; icon: string; description: string }[] = [
  {
    id: 'laboral',
    name: 'Derecho Laboral',
    icon: 'Briefcase',
    description: 'Despidos, liquidaciones, CTS, vacaciones y más',
  },
  {
    id: 'consumidor',
    name: 'Derecho del Consumidor',
    icon: 'ShoppingCart',
    description: 'Reclamos Indecopi, devoluciones, garantías',
  },
  {
    id: 'familia',
    name: 'Derecho de Familia',
    icon: 'Users',
    description: 'Pensión alimenticia, divorcios, tenencia',
  },
  {
    id: 'civil',
    name: 'Derecho Civil',
    icon: 'FileText',
    description: 'Contratos de alquiler, compraventa, deudas',
  },
  {
    id: 'transito',
    name: 'Derecho de Tránsito',
    icon: 'Car',
    description: 'Papeletas, licencias, accidentes',
  },
  {
    id: 'empresas',
    name: 'Constitución de Empresas',
    icon: 'Building',
    description: 'RUC, minuta, estatutos, SAC',
  },
];

export const DOCUMENT_TEMPLATES: DocumentTemplate[] = [
  {
    id: 'carta-reclamo',
    name: 'Carta de Reclamo Simple',
    description: 'Documento formal para presentar un reclamo a una empresa o institución',
    category: 'consumidor',
    price: 'free',
    icon: 'FileText',
    fields: [
      { name: 'nombreCompleto', label: 'Tu nombre completo', type: 'text', required: true },
      { name: 'dni', label: 'DNI', type: 'text', required: true },
      { name: 'direccion', label: 'Tu dirección', type: 'text', required: true },
      { name: 'empresa', label: 'Empresa a reclamar', type: 'text', required: true },
      { name: 'motivo', label: 'Motivo del reclamo', type: 'textarea', required: true },
      { name: 'hechos', label: 'Descripción de los hechos', type: 'textarea', required: true },
      { name: 'peticion', label: '¿Qué solicitas?', type: 'textarea', required: true },
    ],
  },
  {
    id: 'carta-notarial',
    name: 'Carta Notarial de Intimación',
    description: 'Carta formal para exigir el cumplimiento de una obligación',
    category: 'civil',
    price: 49,
    icon: 'ScrollText',
    fields: [
      { name: 'nombreCompleto', label: 'Tu nombre completo', type: 'text', required: true },
      { name: 'dni', label: 'DNI', type: 'text', required: true },
      { name: 'direccion', label: 'Tu dirección', type: 'text', required: true },
      { name: 'destinatario', label: 'Nombre del destinatario', type: 'text', required: true },
      { name: 'direccionDestinatario', label: 'Dirección del destinatario', type: 'text', required: true },
      { name: 'hechos', label: 'Descripción de los hechos', type: 'textarea', required: true },
      { name: 'monto', label: 'Monto adeudado (si aplica)', type: 'number', required: false },
      { name: 'plazo', label: 'Plazo para cumplir (días)', type: 'number', required: true },
    ],
  },
  {
    id: 'contrato-alquiler',
    name: 'Contrato de Alquiler de Vivienda',
    description: 'Contrato completo para arrendamiento de inmueble',
    category: 'civil',
    price: 79,
    icon: 'Home',
    fields: [
      { name: 'arrendador', label: 'Nombre del arrendador (dueño)', type: 'text', required: true },
      { name: 'dniArrendador', label: 'DNI del arrendador', type: 'text', required: true },
      { name: 'arrendatario', label: 'Nombre del arrendatario (inquilino)', type: 'text', required: true },
      { name: 'dniArrendatario', label: 'DNI del arrendatario', type: 'text', required: true },
      { name: 'direccionInmueble', label: 'Dirección del inmueble', type: 'text', required: true },
      { name: 'montoRenta', label: 'Monto de renta mensual (S/.)', type: 'number', required: true },
      { name: 'duracion', label: 'Duración del contrato (meses)', type: 'number', required: true },
      { name: 'garantia', label: 'Meses de garantía', type: 'number', required: true },
      { name: 'fechaInicio', label: 'Fecha de inicio', type: 'date', required: true },
    ],
  },
  {
    id: 'contrato-compraventa',
    name: 'Contrato de Compraventa Simple',
    description: 'Contrato para la venta de bienes muebles',
    category: 'civil',
    price: 79,
    icon: 'HandshakeIcon',
    fields: [
      { name: 'vendedor', label: 'Nombre del vendedor', type: 'text', required: true },
      { name: 'dniVendedor', label: 'DNI del vendedor', type: 'text', required: true },
      { name: 'comprador', label: 'Nombre del comprador', type: 'text', required: true },
      { name: 'dniComprador', label: 'DNI del comprador', type: 'text', required: true },
      { name: 'descripcionBien', label: 'Descripción del bien', type: 'textarea', required: true },
      { name: 'precio', label: 'Precio de venta (S/.)', type: 'number', required: true },
      { name: 'formaPago', label: 'Forma de pago', type: 'select', required: true, options: ['Contado', 'Cuotas', 'Transferencia'] },
    ],
  },
  {
    id: 'carta-despido',
    name: 'Carta de Despido con Liquidación',
    description: 'Modelo para solicitar tu liquidación tras un despido',
    category: 'laboral',
    price: 49,
    icon: 'UserMinus',
    fields: [
      { name: 'nombreTrabajador', label: 'Tu nombre completo', type: 'text', required: true },
      { name: 'dni', label: 'DNI', type: 'text', required: true },
      { name: 'empresa', label: 'Nombre de la empresa', type: 'text', required: true },
      { name: 'fechaIngreso', label: 'Fecha de ingreso a la empresa', type: 'date', required: true },
      { name: 'fechaDespido', label: 'Fecha de despido', type: 'date', required: true },
      { name: 'ultimoSueldo', label: 'Último sueldo mensual (S/.)', type: 'number', required: true },
      { name: 'tipoDespido', label: 'Tipo de despido', type: 'select', required: true, options: ['Arbitrario', 'Con causa', 'Mutuo acuerdo', 'Renuncia'] },
    ],
  },
  {
    id: 'estatuto-sac',
    name: 'Estatuto de Empresa SAC',
    description: 'Estatutos para constituir una Sociedad Anónima Cerrada',
    category: 'empresas',
    price: 149,
    icon: 'Building2',
    fields: [
      { name: 'nombreEmpresa', label: 'Nombre de la empresa', type: 'text', required: true },
      { name: 'objetoSocial', label: 'Objeto social (actividad)', type: 'textarea', required: true },
      { name: 'capital', label: 'Capital social (S/.)', type: 'number', required: true },
      { name: 'socio1Nombre', label: 'Nombre socio 1', type: 'text', required: true },
      { name: 'socio1Dni', label: 'DNI socio 1', type: 'text', required: true },
      { name: 'socio1Porcentaje', label: 'Porcentaje socio 1', type: 'number', required: true },
      { name: 'socio2Nombre', label: 'Nombre socio 2', type: 'text', required: false },
      { name: 'socio2Dni', label: 'DNI socio 2', type: 'text', required: false },
      { name: 'socio2Porcentaje', label: 'Porcentaje socio 2', type: 'number', required: false },
      { name: 'domicilioFiscal', label: 'Domicilio fiscal', type: 'text', required: true },
    ],
  },
  {
    id: 'contrato-servicios',
    name: 'Contrato de Prestación de Servicios',
    description: 'Contrato para servicios profesionales o freelance',
    category: 'civil',
    price: 79,
    icon: 'FileCheck',
    fields: [
      { name: 'prestador', label: 'Nombre del prestador de servicios', type: 'text', required: true },
      { name: 'dniPrestador', label: 'DNI del prestador', type: 'text', required: true },
      { name: 'cliente', label: 'Nombre del cliente', type: 'text', required: true },
      { name: 'dniCliente', label: 'DNI/RUC del cliente', type: 'text', required: true },
      { name: 'descripcionServicio', label: 'Descripción del servicio', type: 'textarea', required: true },
      { name: 'honorarios', label: 'Honorarios (S/.)', type: 'number', required: true },
      { name: 'duracion', label: 'Duración del contrato', type: 'text', required: true },
      { name: 'formaPago', label: 'Forma de pago', type: 'select', required: true, options: ['Mensual', 'Por entregable', 'Al finalizar', 'Adelanto 50%'] },
    ],
  },
  {
    id: 'demanda-alimentos',
    name: 'Demanda de Alimentos (Modelo)',
    description: 'Modelo referencial para demanda de pensión alimenticia',
    category: 'familia',
    price: 99,
    icon: 'Baby',
    fields: [
      { name: 'demandante', label: 'Nombre del demandante (madre/padre)', type: 'text', required: true },
      { name: 'dniDemandante', label: 'DNI del demandante', type: 'text', required: true },
      { name: 'demandado', label: 'Nombre del demandado', type: 'text', required: true },
      { name: 'dniDemandado', label: 'DNI del demandado', type: 'text', required: false },
      { name: 'nombreMenor', label: 'Nombre del menor beneficiario', type: 'text', required: true },
      { name: 'edadMenor', label: 'Edad del menor', type: 'number', required: true },
      { name: 'montoSolicitado', label: 'Monto mensual solicitado (S/.)', type: 'number', required: true },
      { name: 'hechos', label: 'Descripción de los hechos', type: 'textarea', required: true },
    ],
  },
];

export const TESTIMONIALS = [
  {
    name: 'María López',
    role: 'Trabajadora despedida',
    content: 'LegalBot me ayudó a entender mis derechos y recuperar mi CTS en solo 2 semanas. Excelente servicio.',
    rating: 5,
    avatar: 'ML',
  },
  {
    name: 'Carlos Mendoza',
    role: 'Emprendedor',
    content: 'Constituí mi SAC sin gastar en abogados caros. Los documentos estaban perfectos y listos para notaría.',
    rating: 5,
    avatar: 'CM',
  },
  {
    name: 'Ana García',
    role: 'Propietaria',
    content: 'El contrato de alquiler que generé me ahorró problemas con un inquilino moroso. Muy recomendado.',
    rating: 5,
    avatar: 'AG',
  },
  {
    name: 'Roberto Sánchez',
    role: 'Consumidor',
    content: 'Gracias a LegalBot supe cómo reclamar en Indecopi y me devolvieron mi dinero. ¡Increíble!',
    rating: 5,
    avatar: 'RS',
  },
];

export const FAQ = [
  {
    question: '¿LegalBot reemplaza a un abogado?',
    answer: 'No. LegalBot es una herramienta informativa que te ayuda a entender tus derechos y generar documentos básicos. Para casos complejos, penales o de alto riesgo, siempre recomendamos consultar con un abogado titulado.',
  },
  {
    question: '¿Los documentos generados son legales?',
    answer: 'Los documentos son modelos referenciales basados en la legislación peruana vigente. Dependiendo del tipo de documento, algunos requerirán legalización notarial o firmas adicionales para tener validez legal completa.',
  },
  {
    question: '¿Puedo cancelar mi suscripción en cualquier momento?',
    answer: 'Sí, puedes cancelar tu suscripción en cualquier momento desde tu dashboard. Seguirás teniendo acceso hasta el final del período pagado.',
  },
  {
    question: '¿Qué métodos de pago aceptan?',
    answer: 'Aceptamos tarjetas de crédito y débito (Visa, Mastercard, American Express) a través de Culqi, la pasarela de pagos más segura del Perú.',
  },
  {
    question: '¿Cómo funciona la videollamada con abogado?',
    answer: 'Los usuarios Premium tienen derecho a una videollamada de 30 minutos al mes con un abogado colegiado de nuestra red. Puedes agendar desde tu dashboard.',
  },
  {
    question: '¿Mis datos están seguros?',
    answer: 'Absolutamente. Utilizamos encriptación de grado bancario y nunca compartimos tu información personal con terceros. Cumplimos con la Ley de Protección de Datos Personales del Perú.',
  },
];

